apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-w
  namespace: svc-fw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-w
  template:
    metadata:
      labels:
        app: service-w
    spec:
      containers:
      - name: service-w
        image: service-w:latest
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://service-a.svc-fw.svc.cluster.local:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: service-w
  namespace: svc-fw
spec:
  selector:
    app: service-w
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
