apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  namespace: svc-fw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
      - name: service-d
        image: service-d:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "<your-secret-password>"
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
  namespace: svc-fw
spec:
  selector:
    app: service-d
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
